import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { useEffect } from "react";
import { useRouter } from "next/router";
import Loader from "@/components/Loader";

const Home: NextPage = () => {
  // if has no session, will redirect to /api/auth/signin
  const { data: sessionData, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (sessionData?.user) {
      router.push("/dashboard");
    }
  }, [sessionData]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>{status === "loading" && <Loader />}</>
    </>
  );
};

export default Home;
